### ISSUE TITLE
Issue with setting locale in templates

### ISSUE THREAD

**Issue by alecritson** [sjelfull/Craft-Faker#5]
Hello!

Thanks for the plugin, it's super handy although I found an issue when trying to set the locale to `en_GB`.

Using the following syntax

``` twig
{% set fake = craft.faker.locale('en_GB').fake() %}
```

Gives the error `Craft\FakerService and its behaviors do not have a method or closure named "fake"`  since the `locale()` method returns to the service object, which doesn't have the correct method.

I've found a fix, so I'll set up a pull request for you to take a look at :).

**Comment by sjelfull** [comment]
Awesome, thanks!
